service: retro
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeys:
      - ${opt:stage}-initial-key

plugins:
  - serverless-webpack

functions:
  health:
    handler: src/health.handle
    events:
      - http:
          method: get
          path: /
          private: true

package:
  individually: true

custom:
  webpack:
    includeModules: false
    keepOutputDirectory: true
