service: retro
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          method: get
          path: /
